//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../BASIC.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBASICListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public partial class BASICBaseListener : IBASICListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.remarkstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemarkstatement([NotNull] BASICParser.RemarkstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.remarkstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemarkstatement([NotNull] BASICParser.RemarkstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] BASICParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] BASICParser.LineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.linenumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinenumber([NotNull] BASICParser.LinenumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.linenumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinenumber([NotNull] BASICParser.LinenumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.endline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndline([NotNull] BASICParser.EndlineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.endline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndline([NotNull] BASICParser.EndlineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.endstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndstatement([NotNull] BASICParser.EndstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.endstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndstatement([NotNull] BASICParser.EndstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] BASICParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] BASICParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.numericconstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericconstant([NotNull] BASICParser.NumericconstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.numericconstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericconstant([NotNull] BASICParser.NumericconstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.sign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSign([NotNull] BASICParser.SignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.sign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSign([NotNull] BASICParser.SignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.numericrep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericrep([NotNull] BASICParser.NumericrepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.numericrep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericrep([NotNull] BASICParser.NumericrepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.significand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSignificand([NotNull] BASICParser.SignificandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.significand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSignificand([NotNull] BASICParser.SignificandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger([NotNull] BASICParser.IntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger([NotNull] BASICParser.IntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.fraction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFraction([NotNull] BASICParser.FractionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.fraction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFraction([NotNull] BASICParser.FractionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.exrad"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExrad([NotNull] BASICParser.ExradContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.exrad"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExrad([NotNull] BASICParser.ExradContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.stringconstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringconstant([NotNull] BASICParser.StringconstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.stringconstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringconstant([NotNull] BASICParser.StringconstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] BASICParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] BASICParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.numericvariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericvariable([NotNull] BASICParser.NumericvariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.numericvariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericvariable([NotNull] BASICParser.NumericvariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.simplenumericvariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimplenumericvariable([NotNull] BASICParser.SimplenumericvariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.simplenumericvariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimplenumericvariable([NotNull] BASICParser.SimplenumericvariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.numericarrayelement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericarrayelement([NotNull] BASICParser.NumericarrayelementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.numericarrayelement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericarrayelement([NotNull] BASICParser.NumericarrayelementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.numericarrayname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericarrayname([NotNull] BASICParser.NumericarraynameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.numericarrayname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericarrayname([NotNull] BASICParser.NumericarraynameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.subscript"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubscript([NotNull] BASICParser.SubscriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.subscript"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubscript([NotNull] BASICParser.SubscriptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.stringvariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringvariable([NotNull] BASICParser.StringvariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.stringvariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringvariable([NotNull] BASICParser.StringvariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] BASICParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] BASICParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.numericexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericexpression([NotNull] BASICParser.NumericexpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.numericexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericexpression([NotNull] BASICParser.NumericexpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] BASICParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] BASICParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] BASICParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] BASICParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.multiplier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplier([NotNull] BASICParser.MultiplierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.multiplier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplier([NotNull] BASICParser.MultiplierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] BASICParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] BASICParser.PrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.numericfunctionref"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericfunctionref([NotNull] BASICParser.NumericfunctionrefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.numericfunctionref"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericfunctionref([NotNull] BASICParser.NumericfunctionrefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.numericfunctionname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericfunctionname([NotNull] BASICParser.NumericfunctionnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.numericfunctionname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericfunctionname([NotNull] BASICParser.NumericfunctionnameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.argumentlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentlist([NotNull] BASICParser.ArgumentlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.argumentlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentlist([NotNull] BASICParser.ArgumentlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] BASICParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] BASICParser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.stringexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringexpression([NotNull] BASICParser.StringexpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.stringexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringexpression([NotNull] BASICParser.StringexpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.numericsuppliedfunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericsuppliedfunction([NotNull] BASICParser.NumericsuppliedfunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.numericsuppliedfunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericsuppliedfunction([NotNull] BASICParser.NumericsuppliedfunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.defstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefstatement([NotNull] BASICParser.DefstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.defstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefstatement([NotNull] BASICParser.DefstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.numericdefinedfunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericdefinedfunction([NotNull] BASICParser.NumericdefinedfunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.numericdefinedfunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericdefinedfunction([NotNull] BASICParser.NumericdefinedfunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.parameterlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterlist([NotNull] BASICParser.ParameterlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.parameterlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterlist([NotNull] BASICParser.ParameterlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] BASICParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] BASICParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.letstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLetstatement([NotNull] BASICParser.LetstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.letstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLetstatement([NotNull] BASICParser.LetstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.numericletstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericletstatement([NotNull] BASICParser.NumericletstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.numericletstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericletstatement([NotNull] BASICParser.NumericletstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.stringletstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringletstatement([NotNull] BASICParser.StringletstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.stringletstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringletstatement([NotNull] BASICParser.StringletstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.gotostatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotostatement([NotNull] BASICParser.GotostatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.gotostatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotostatement([NotNull] BASICParser.GotostatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.ifthenstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfthenstatement([NotNull] BASICParser.IfthenstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.ifthenstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfthenstatement([NotNull] BASICParser.IfthenstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.relationalexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalexpression([NotNull] BASICParser.RelationalexpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.relationalexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalexpression([NotNull] BASICParser.RelationalexpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.relation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelation([NotNull] BASICParser.RelationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.relation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelation([NotNull] BASICParser.RelationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.equalityrelation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityrelation([NotNull] BASICParser.EqualityrelationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.equalityrelation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityrelation([NotNull] BASICParser.EqualityrelationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.notless"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotless([NotNull] BASICParser.NotlessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.notless"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotless([NotNull] BASICParser.NotlessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.notgreater"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotgreater([NotNull] BASICParser.NotgreaterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.notgreater"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotgreater([NotNull] BASICParser.NotgreaterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.notequals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotequals([NotNull] BASICParser.NotequalsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.notequals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotequals([NotNull] BASICParser.NotequalsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.gosubstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGosubstatement([NotNull] BASICParser.GosubstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.gosubstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGosubstatement([NotNull] BASICParser.GosubstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.returnstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnstatement([NotNull] BASICParser.ReturnstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.returnstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnstatement([NotNull] BASICParser.ReturnstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.ongotostatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOngotostatement([NotNull] BASICParser.OngotostatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.ongotostatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOngotostatement([NotNull] BASICParser.OngotostatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.stopstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStopstatement([NotNull] BASICParser.StopstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.stopstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStopstatement([NotNull] BASICParser.StopstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.forstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForstatement([NotNull] BASICParser.ForstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.forstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForstatement([NotNull] BASICParser.ForstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.controlvariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterControlvariable([NotNull] BASICParser.ControlvariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.controlvariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitControlvariable([NotNull] BASICParser.ControlvariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.initialvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitialvalue([NotNull] BASICParser.InitialvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.initialvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitialvalue([NotNull] BASICParser.InitialvalueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.limit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLimit([NotNull] BASICParser.LimitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.limit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLimit([NotNull] BASICParser.LimitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.increment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncrement([NotNull] BASICParser.IncrementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.increment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncrement([NotNull] BASICParser.IncrementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.nextstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNextstatement([NotNull] BASICParser.NextstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.nextstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNextstatement([NotNull] BASICParser.NextstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.printstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintstatement([NotNull] BASICParser.PrintstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.printstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintstatement([NotNull] BASICParser.PrintstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.printlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintlist([NotNull] BASICParser.PrintlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.printlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintlist([NotNull] BASICParser.PrintlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.printitem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintitem([NotNull] BASICParser.PrintitemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.printitem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintitem([NotNull] BASICParser.PrintitemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.printseparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintseparator([NotNull] BASICParser.PrintseparatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.printseparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintseparator([NotNull] BASICParser.PrintseparatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.inputstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputstatement([NotNull] BASICParser.InputstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.inputstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputstatement([NotNull] BASICParser.InputstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.dimensionstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDimensionstatement([NotNull] BASICParser.DimensionstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.dimensionstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDimensionstatement([NotNull] BASICParser.DimensionstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.bounds"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBounds([NotNull] BASICParser.BoundsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.bounds"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBounds([NotNull] BASICParser.BoundsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.readstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReadstatement([NotNull] BASICParser.ReadstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.readstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReadstatement([NotNull] BASICParser.ReadstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.writestatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWritestatement([NotNull] BASICParser.WritestatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.writestatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWritestatement([NotNull] BASICParser.WritestatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.filename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilename([NotNull] BASICParser.FilenameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.filename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilename([NotNull] BASICParser.FilenameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.randomizestatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRandomizestatement([NotNull] BASICParser.RandomizestatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.randomizestatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRandomizestatement([NotNull] BASICParser.RandomizestatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.stringcharacter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringcharacter([NotNull] BASICParser.StringcharacterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.stringcharacter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringcharacter([NotNull] BASICParser.StringcharacterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.quotedstringcharacter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuotedstringcharacter([NotNull] BASICParser.QuotedstringcharacterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.quotedstringcharacter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuotedstringcharacter([NotNull] BASICParser.QuotedstringcharacterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.unquotedstringcharacter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnquotedstringcharacter([NotNull] BASICParser.UnquotedstringcharacterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.unquotedstringcharacter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnquotedstringcharacter([NotNull] BASICParser.UnquotedstringcharacterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.plainstringcharacter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlainstringcharacter([NotNull] BASICParser.PlainstringcharacterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.plainstringcharacter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlainstringcharacter([NotNull] BASICParser.PlainstringcharacterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.remarkstring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemarkstring([NotNull] BASICParser.RemarkstringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.remarkstring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemarkstring([NotNull] BASICParser.RemarkstringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.quotedstring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuotedstring([NotNull] BASICParser.QuotedstringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.quotedstring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuotedstring([NotNull] BASICParser.QuotedstringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.unquotedstring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnquotedstring([NotNull] BASICParser.UnquotedstringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.unquotedstring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnquotedstring([NotNull] BASICParser.UnquotedstringContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
